### ISSUE TITLE
Feature request: Include functionality

### ISSUE THREAD

**Issue by bbaserdem** [andreyv/sbupdate#19]
I am distributing configs through etckeeper across my computers. For my use case, it could be useful to have a line such as `#include /etc/sbupdate.local.conf`, so I could give generic options in /etc/sbupdate.conf, which can be shared accross devices; and device specific info on some file that will be distributed in some other way.

**Comment by andreyv** [comment]
The config file is a Bash script. You can do
```bash
[[ -f "/etc/sbupdate.local.conf" ]] && source "/etc/sbupdate.local.conf"
```
in the config.

**Comment by bbaserdem** [comment]
Oh did not realize that is was a bash script. Then functionality already exists.
