### ISSUE TITLE
Kernel parameters in the initramfs?

### ISSUE THREAD

**Issue by bbaserdem** [andreyv/sbupdate#31]
If the initramfs has embedded parameters (I'm planning to do this with dracut); will the unified image retain those parameters without specifying them again in the sbupdate.conf ? I looked through the script; but could not gather an answer on my own.

**Comment by andreyv** [comment]
Hi,

I'm not aware of the possibility to set kernel command line in the initramfs (when the initramfs is unpacked, the boot is already in progress, after all).

sbupdate always sets the kernel command line in the UEFI image. You could modify the source by removing the `.cmdline` section from the image. This will cause the kernel to be booted without a command line, but still with initramfs.

**Comment by bbaserdem** [comment]
dracut can include kernel parameters by putting files at `/etc/cmdline.d/*.conf` and lines will be accepted as kernel parameters; if I am not mistaken. I am unfamiliar with the details of the boot process; so I don't know what would override what exactly. I will do so; thank you.

**Comment by andreyv** [comment]
Then these files would correspond to `CMDLINE_DEFAULT` etc. in `sbupdate.conf`. sbupdate doesn't currently support `/etc/cmdline`; however, `sbupdate.conf` is a Bash script, and so you can write code that reads these files and constructs the final command line inside `sbupdate.conf`.

Something like this:
```shell
CMDLINE_DEFAULT="$(cat /etc/cmdline*)"
```
