### ISSUE TITLE
Is it possible to enable secureboot without erasing the existing OS?

### ISSUE THREAD

**Issue by 1m-N00b** [andreyv/sbupdate#33]
i use arch os now.And I only have one desktop.
I'm planning to buy a new laptop next year and would like to implement secureboot on it
But I want to try secureboot with my existing OS because I'm buying a dell xps15-like laptop with higher and better specs and I don't want to mess with it and break it.If you can't implement it without wiping the existing OS, is there any way to do it, such as virtualization?

**Comment by Maryse47** [comment]
Secureboot doesn't require wiping existing OS. You just need to sign files used to boot (which is what this tool does), nothing else changes.

**Comment by 1m-N00b** [comment]
I see. So you can use it to create keys as you would in tuto, and you can implement secureboot by checking the box to enable secureboot in bios?Is that correct in my opinion?

**Comment by Maryse47** [comment]
Yes, you can enable secureboot for existing system by following this project readme and enabling it in bios.

**Comment by 1m-N00b** [comment]
thx
