### ISSUE TITLE
Testing 

### ISSUE THREAD

**Issue by ispanos** [andreyv/sbupdate#37]
Forgive my ignorance, I've just managed to boot my first unified kernel image.
I found this repo from [this page](https://wiki.archlinux.org/index.php/Unified_Extensible_Firmware_Interface/Secure_Boot#Fully_automated_unified_kernel_generation_and_signing_with_sbupdate) and I am wondering if there should be a trigger for downgrades. I'm not sure how `Operation = Upgrade` works when `Target= ` is a file.

Regarding ` Add tests (how?)`, how can I contact you? I've been working on an  ansible playbook to configure the installation process. I might be able to work something out using btrfs snapshots, combined with [`timeshift-autosnap`](https://gitlab.com/gobonja/timeshift-autosnap). There's also [`grub-btrfs`](https://github.com/Antynea/grub-btrfs), which creates new  grub entries for snapshots. There may be a way to modify it and [create new Grub entries for new images](https://wiki.archlinux.org/index.php/GRUB#Chainloading_a_unified_kernel_image).

**Comment by andreyv** [comment]
Hi,

`Upgrade` also triggers when the version is downgraded. See [`alpm-hooks(5)`](https://man.archlinux.org/man/alpm-hooks.5):
> Installations are considered an upgrade if the package or file is already present on the system regardless of whether the new package version is actually greater than the currently installed version.

Regarding tests: The test suite should be such that it can run automatically on Github Actions or locally. This would likely use `pacstrap` and `arch-chroot` for each individual test, and wouldn't attempt any actual booting, but just verify state after running `sbupdate`. A more advanced version would boot the result using QEMU with OVMF firmware.

**Comment by ispanos** [comment]
Alright, I'll keep it in mind and I might open a new issue if I think of something.
