### ISSUE TITLE
Output filename for kernel?

### ISSUE THREAD

**Issue by farwayer** [andreyv/sbupdate#40]
In some cases it can be useful.

**Comment by ntkoopman** [comment]
Probably not intentional, but you can do this right now by overriding a function:

sbupdate.conf:
```sh
# $1: image name
output_name() {
  echo "${ESP_DIR}/EFI/BOOT/BOOTx64.EFI"
}
```

**Comment by farwayer** [comment]
@ntkoopman Cool! It works. Than you.
