### ISSUE TITLE
signed unified kernel image file name

### ISSUE THREAD

**Issue by beroal** [andreyv/sbupdate#42]
> For each installed Arch kernel, a signed UEFI image will be generated, by default in `/boot/EFI/Arch/<NAME>-signed.efi`.

Is it possible to redefine the file name? For example, I want to write a signed unified kernel image to `<EFI_SYSTEM_PARTITION>\EFI\BOOT\BOOTX64.EFI`. This may be specified as an option `OUT_FILE[<NAME>]` where `<NAME>` is a kernel name.

**Comment by andreyv** [comment]
Thanks, this is now implemented as suggested, using the name `OUTPUT`.
