### ISSUE TITLE
SBAT support for new shim

### ISSUE THREAD

**Issue by solsticedhiver** [andreyv/sbupdate#48]
The newer shim (shim-signed 15.4) requires a SBAT section for the EFI binary.

https://github.com/rhboot/shim/blob/main/SBAT.md

Please add support to sign kernels with an appropriate SBAT section to boot with the new shim-signed package.

**Comment by Maryse47** [comment]
This project works with custom Secure Boot keys so why would you need shim?

**Comment by solsticedhiver** [comment]
Never mind, There is already a .sbat section. possibly created by sbsign.

**Comment by Maryse47** [comment]
I was pointing out that using some intermediary efi image like shim is inferior if you can load kernel directly instead.
