### ISSUE TITLE
[Feature Request] Please add option to add an extra initrd to efi image

### ISSUE THREAD

**Issue by Taijian** [andreyv/sbupdate#52]
Hi there,

I have been using your excellent tool for quite a number of years now and have recently migrated my system to a new laptop. Unfortunately, this one has a small bug in it`s ACPI implementation under Linux (because of course it does), so that I want/need to load a modified ACPI table during boot in order to fix S3sleep. I would therefore like to automagically incorporate this blob into my efi image that sbupdate compiles and signs.

I have provisionally done this by:

1. Adding a new variable to sbupdate.conf - `INITRD_EXTRA`
2. Adding that new vriable into the `objcopy` part of sbupdate, by simply adding it in between `INITRD_PREPEND` and `initrd`

Do you think, that you might put something like this into the official release?

Thank you for all your work creating and sharing this very helpful piece of software!

**Comment by andreyv** [comment]
Hi,

This is already supported by the undocumented variable that you mentioned. You can just do
```bash
INITRD_PREPEND+=("extra.img")
```
in the configuration file.

**Comment by Taijian** [comment]
Thank you, that was EXACTLY what I was looking for. 

Maybe you could mention it in the readme? Just so people can have an easier time finding it.
