### ISSUE TITLE
issue with systemd 252.1

### ISSUE THREAD

**Issue by solsticedhiver** [andreyv/sbupdate#58]
I am not sure yet this is related to *sbupdate* but something fishy is going on and it seems related to the cmdline options passed to the kernel. so.

Since I updated to systemd 252.1 on my laptop, the boot breaks because of the error `"Failed to start Loading Kernel Modules"`
Specifically, my **CMDLINE_DEFAULT** in `/etc/sbupdate.conf` ends wtih `i915.fastboot=1` but the error above is caused because there is garbage appended after the 1 of the parameter. So this trhows: `i915: 1\ygyjfhgjfghj invalid parameter for fastboot`

I thought that my FAT32 ESP was corrupt but it does not seem so

Simply reverting to systemd 251.7 fixes the problem???

Moreover, on my desktop, the boot is also broken because of /dev/vg/swap is not found by systemd, and the boot halts indefintely there.
I was thinking it is related to some lvm device not showing up, like I said in https://bugs.archlinux.org/task/76518

But now I am wondering because `resume=/dev/vg/swap` is also at the end of my **CMDLINE_DEFAULT** there. But I did not see any weird message lke above, So?

There again I downgraded systemd to 251.7
![IMG_20221112_024826](https://user-images.githubusercontent.com/105990/201452570-496018a1-6a24-4018-bddc-b16f1fa8198f.jpg)

**Comment by andreyv** [comment]
systemd bug report: https://github.com/systemd/systemd/issues/25201

As a workaround you can add `\0` at the end of `CMDLINE_DEFAULT` for now.

**Comment by andreyv** [comment]
Added a workaround in 53e6b66122bcec858a1b92bf6c96fa0cc6939dd8.

**Comment by solsticedhiver** [comment]
It is working fine with latest r131.4926075
Both on my laptop and desktop. So my intuition was good for the later.

Thanks
